name: CI tests

on: [push, pull_request]

jobs:

  Run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.8']
    steps:

    - uses: actions/checkout@v1
      with:
        submodules: recursive

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install
      run: |
        sudo apt-get update
        sudo apt-get install clang-format-8 g++-8 xsltproc git
        pip install --upgrade -r requirements.txt

    - name: Check formatting
      run: source .github/workflows/format.sh

    - name: ccache
      uses: hendrikmuhs/ccache-action@v1

    - name: Get and build tools
      run: |
        export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
        make build
        git clone https://github.com/Xilinx/RapidWright.git $GITHUB_WORKSPACE/RapidWright
        git clone https://github.com/capnproto/capnproto-java.git $GITHUB_WORKSPACE/capnproto-java
        git clone https://github.com/SymbiFlow/fpga-interchange-schema.git

    - name: Test
      run: source .github/workflows/test.sh
